tls:
  certificates:
    - certFile: /etc/traefik/certs/dev.sby.test.crt
      keyFile: /etc/traefik/certs/dev.sby.test.key
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/dev.sby.test.crt
        keyFile: /etc/traefik/certs/dev.sby.test.key
